# Generated by Django 4.2.11 on 2025-02-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.FloatField()),
                ('water_temperature', models.FloatField()),
                ('tds_level', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hydroponic_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='hydroponic_system.hydroponicsystem')),
            ],
        ),
    ]
